# Generated by Django 4.1 on 2023-11-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateadded', models.DateField(default=django.utils.timezone.now)),
                ('dateupdated', models.DateField(default=django.utils.timezone.now)),
                ('stock', models.IntegerField(default=1)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
