# Generated by Django 4.1 on 2024-02-17 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateadded', models.DateTimeField(auto_now=True)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('stock_S', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_M', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_L', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_stack', models.IntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
