# Generated by Django 4.1 on 2024-02-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_XXL',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
