# Generated by Django 4.1 on 2024-02-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_stock_xxl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_stack',
        ),
    ]
