# Generated by Django 4.1 on 2023-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_stack',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
