# Generated by Django 4.1 on 2023-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_product_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_stack',
            field=models.IntegerField(default=1),
        ),
    ]
